version: '3.4'

networks:
  frontend:
  backend:

services:
  myeventcatalogapi:
    image: event/myeventcatalogapi
    build:
      context: .\EventCatalogApi
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:7812
      DatabaseServer: mymssqlserver
      DatabaseName: MyEventDB
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "7812:80"
    depends_on:
      - mymssqlserver
    networks:
      - frontend
      - backend
    container_name: MyEventProductserver
  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:7813
    ports:
      - "7800:80"
    container_name: mytokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mymssqlserver

  webmvc:
    image: events/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      EventUrl: http://myeventcatalogapi
      IdentityUrl: http://192.168.254.29:7800
      CallBackUrl: http://localhost:7813
    ports:
      - "7813:80"
    container_name: Mywebshop
    networks:
      - frontend
    depends_on:
      - myeventcatalogapi

  mymssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1449:1433"
    container_name: myeventsqlserver
    networks:
      - backend