version: '3.4'

networks:
  frontend:
  backend:

services:
  myeventcatalogapi:
    image: event/myeventcatalogapi
    build:
      context: .\EventCatalogApi
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:7812
      DatabaseServer: mymssqlserver
      DatabaseName: MyEventDB
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "7812:80"
    depends_on:
      - mymssqlserver
    networks:
      - frontend
      - backend
    container_name: MyEventProductserver


  mytokenserver:
    image: event/mytokenapi
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:7813
    ports:
      - "7800:80"
    container_name: mytokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mymssqlserver

  cart:
    image: event/cartapi
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    environment:
      IdentityUrl: http://192.168.254.29:7800
      ConnectionString : basket.data      
    ports:
      - "7830:80"
    container_name: cartapi
    networks:
      - backend
      - frontend
    depends_on:
      - mytokenserver
      - basket.data
  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: events/orderapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.254.29:7800
      DatabaseServer: mymssqlserver
      DatabaseName: OrdersDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "7830:80"
    container_name: orderapi
    networks:
      - backend
      - frontend
    depends_on:
      - mymssqlserver
      - mytokenserver

  webmvc:
    image: events/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      EventUrl: http://myeventcatalogapi
      IdentityUrl: http://192.168.254.29:7800
      CallBackUrl: http://localhost:7813
      CartUrl: http://cart
    ports:
      - "7813:80"
    container_name: Mywebshop
    networks:
      - frontend
    depends_on:
      - myeventcatalogapi
      - mytokenserver
      - cart

  mymssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1449:1433"
    container_name: myeventsqlserver
    networks:
      - backend

  basket.data:
    image: redis
    container_name: basketdata
    ports:
      - "7080:6379"
    networks:
      - backend